title: Simplicity

description: >- # this means to ignore newlines until "baseurl:"
  A personal site about Adam Weiss, software development, and leadership.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.adamweiss.me # the base hostname & protocol for your site, e.g. http://example.com
teaser: /assets/img/placeholder.jpg
repository: amweiss/amweiss.github.io

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.25.0

# Social Sharing
og_image: /assets/img/placeholder.jpg

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York
minimal_mistakes_skin: default
search: true

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Adam Weiss
  avatar: /assets/img/headshot7.jpg
  bio: Development leader with a belief that simple solutions result in better products.
  location: Buffalo, NY
  email: adam@adamweiss.me
  # twitter: amweiss
  github: amweiss
  linkedin: adammweiss
  # stackoverflow: 149866/adam-w

footer:
  links:
    - label: Home
      icon: fas fa-home
      url: https://www.adamweiss.me
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/amweiss/amweiss.github.io

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
